Add support for custom updaters (/etc/genup/updaters.d)
Addresses issues:
 * https://github.com/sakaki-/genup/issues/4
 * https://github.com/sakaki-/genup/issues/5

Thanks to ngerstle, iperi for requesting.

diff --git a/genup b/genup
--- a/genup
+++ b/genup
@@ -5,7 +5,7 @@
 # Will offer to update the kernel, if a new version has become available.
 # Intended to be run interactively.
 #
-# Copyright (c) 2014-2015 sakaki <sakaki@deciban.com>
+# Copyright (c) 2014-2016 sakaki <sakaki@deciban.com>
 #
 # License (GPL v3.0)
 # ------------------
@@ -23,13 +23,15 @@
 
 set -e
 set -u
+shopt -s nullglob
 
 # Scroll to the bottom of this script to follow the main program flow.
 
 # ********************** variables ********************* 
 PROGNAME="$(basename "${0}")"
-VERSION="1.0.10"
+VERSION="1.0.11"
 ETCPROFILE="/etc/profile"
+UPDATERSDIR="/etc/${PROGNAME}/updaters.d"
 RED_TEXT="" GREEN_TEXT="" YELLOW_TEXT="" RESET_ATTS="" ALERT_TEXT=""
 if [[ -v TERM && -n "${TERM}" && "${TERM}" != "dumb" ]]; then
     RED_TEXT="$(tput setaf 1)$(tput bold)"
@@ -66,7 +68,7 @@ declare -i ARG_ASK=0 ARG_DEPLOYFROMSTAGING=0 ARG_HELP=0 ARG_NO_KERNEL_UPGRADE=0
 declare -i ARG_VERBOSE=0 ARG_VERSION=0 ARG_DISPATCHCONF=0
 declare -i ARG_KEEP_OLD_DISTFILES=0
 declare -i ARG_NO_PERL_CLEANER=0 ARG_NO_PYTHON_UPDATER=0 ARG_ALERT=0
-declare -i ARG_IGNORE_REQUIRED_CHANGES=0
+declare -i ARG_IGNORE_REQUIRED_CHANGES=0 ARG_NO_CUSTOM_UPDATERS=0
 
 # ***************** various functions ****************** 
 cleanup_and_exit_with_code() {
@@ -281,6 +283,26 @@ bring_old_python_modules_up_to_date() {
         python-updater ${VERBOSITYFLAG}
     fi
 }
+run_custom_updaters_if_present() {
+    # if not inhibited, find any executable files in the /etc/genup/updaters.d
+    # top-level directory (resolving symlinks) and execute them in turn,
+    # failing if any returns a non-zero exit code
+    local NEXTPATH
+    local REALPATH
+    if ((ARG_NO_CUSTOM_UPDATERS==0)); then
+        if [ -d "${UPDATERSDIR}" ]; then
+            for NEXTPATH in "${UPDATERSDIR}"/*; do
+                REALPATH="$(readlink --canonicalize "${NEXTPATH}")"
+                if [[ -f "${REALPATH}" && -s "${REALPATH}" && -x "${REALPATH}" ]]; then
+                    show "Running custom updater '${NEXTPATH}'..."
+                    if ! "${REALPATH}"; then
+                        die "Error running custom updater '${NEXTPATH}'"
+                    fi
+                fi
+            done
+        fi
+    fi
+}
 check_if_dispatch_conf_needs_to_be_run() {
     # check if the user has any configuration file changes pending review
     # by dispatch-conf, and set the NEEDSDISPATCHCONF variable accordingly
@@ -439,6 +461,9 @@ Options:
                         (staging) buildkernel invocation (requires buildkernel
                         USE flag to have been set)
   -c, --dispatch-conf   run dispatch-conf, even if in non-interactive mode
+  -C, --no-custom-updaters
+                        do not run any custom updaters from the
+                        /etc/genup/updaters.d directory
   -d, --deploy-from-staging
                         if an updated kernel is successfully built in staging,
                         afterwards try to copy it onto the EFI system partition
@@ -526,7 +551,7 @@ process_command_line_options() {
     declare -i RC
     set +e
         # error trapping off, as we want to handle errors
-        TEMP="$(getopt -o aAb:cde:hiknpPvV --long ask,alert,buildkernel-args:,dispatch-conf,deploy-from-staging,emerge-args:,help,ignore-required-changes,keep-old-distfiles,no-kernel-upgrade,no-perl-cleaner,no-python-updater,verbose,version -n "${PROGNAME}" -- "${@}")"
+        TEMP="$(getopt -o aAb:cCde:hiknpPvV --long ask,alert,buildkernel-args:,dispatch-conf,no-custom-updaters,deploy-from-staging,emerge-args:,help,ignore-required-changes,keep-old-distfiles,no-kernel-upgrade,no-perl-cleaner,no-python-updater,verbose,version -n "${PROGNAME}" -- "${@}")"
         RC="${?}"
     set -e
     if ((RC!=0)); then
@@ -545,6 +570,7 @@ process_command_line_options() {
                     *) BUILDKERNELARGS="${2}" ; shift 2 ;;
                 esac ;;
             -c|--dispatch-conf) ARG_DISPATCHCONF=1 ; shift ;;
+            -C|--no-custom-updaters) ARG_NO_CUSTOM_UPDATERS=1 ; shift ;;
             -d|--deploy-from-staging) ARG_DEPLOYFROMSTAGING=1 ; shift ;;
             -e|--emerge-args)
                 case "${2}" in
@@ -617,6 +643,7 @@ rebuild_packages_depending_on_stale_libraries
 purge_old_distfiles_if_desired
 copy_new_kernel_from_staging_if_present_and_desired
 update_environment
+run_custom_updaters_if_present
 display_final_status
 cleanup_and_exit_with_code 0
 # **************** end of script proper ****************
