Force set TERM variable if tty -s fails
For example, when running from a cron script; otherwise mach builds such
as firefox will fail.

diff --git a/genup b/genup
--- a/genup
+++ b/genup
@@ -5,7 +5,7 @@
 # Will offer to update the kernel, if a new version has become available.
 # Intended to be run interactively.
 #
-# Copyright (c) 2014-2017 sakaki <sakaki@deciban.com>
+# Copyright (c) 2014-2018 sakaki <sakaki@deciban.com>
 #
 # License (GPL v3.0)
 # ------------------
@@ -29,7 +29,7 @@ shopt -s nullglob
 
 # ********************** variables ********************* 
 PROGNAME="$(basename "${0}")"
-VERSION="1.0.15"
+VERSION="1.0.16"
 ETCPROFILE="/etc/profile"
 UPDATERSDIR="/etc/${PROGNAME}/updaters.d"
 RED_TEXT="" GREEN_TEXT="" YELLOW_TEXT="" RESET_ATTS="" ALERT_TEXT=""
@@ -74,6 +74,11 @@ declare -i ARG_NO_PERL_CLEANER=0
 declare -i ARG_NO_EIX_SYNC=0 ARG_ALERT=0
 declare -i ARG_IGNORE_REQUIRED_CHANGES=0 ARG_NO_CUSTOM_UPDATERS=0
 declare -i ADJUSTMENT=19
+# force TERM if none found (e.g. when running from cron)
+# otherwise mach builds (firefox etc.) will fail
+if ! tty -s; then
+    export TERM="dumb"
+fi
 
 # ***************** various functions ****************** 
 cleanup_and_exit_with_code() {
